# Generated by Django 5.2.8 on 2025-11-21 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("full_path", models.CharField(max_length=500, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("parent_path", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["full_path"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_code", models.CharField(max_length=100, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vat", models.CharField(blank=True, max_length=20)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("barcode", models.CharField(blank=True, max_length=100)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("producer", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("short_description", models.TextField(blank=True)),
                ("stock", models.IntegerField(default=0)),
                ("availability", models.CharField(blank=True, max_length=100)),
                ("delivery", models.CharField(blank=True, max_length=100)),
                ("currency", models.CharField(default="EUR", max_length=10)),
                ("seo_url", models.CharField(blank=True, max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="pages.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
