# Generated by Django 5.2.8 on 2025-11-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
