# Generated by Django 5.2.8 on 2025-11-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_category_image_category_image_url_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images_json",
            field=models.TextField(blank=True),
        ),
    ]
